### ISSUE TITLE
ExamTopics allows everyone to view 10 questions on page by default.

### ISSUE THREAD

**Issue by AppleSilicon** [kamsec/ExamTopics-Question-Filter#1]
Without logging in to ExamTopics, it allows everyone to view 10 questions on page by default. Please allow me to create a branch, so i can create a PR.

https://github.com/kamsec/ExamTopics-Question-Filter/blob/db996e9d9aded2fc680076a19bf52a3288417054/script.js#L16

**Comment by kamsec** [comment]
Hi,
yeah, seems like they changed it recently, so you are right, it should be changed to 10.
However, you can fork this repo, create a branch, make change, and then make a PR, as described here:
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
